// Country list for the SERP Overview country picker. Mirrors EXACTLY the
// codes documented for Ahrefs' /serp-overview endpoint (210 codes, per
// https://docs.ahrefs.com/en/api/reference/serp-overview/get-serp-overview,
// checked 2026-07-10) — not the full ISO 3166-1 set: Ahrefs has no SERP
// data for e.g. ir/sd/sy/bm, and it DOES support a few non-obvious ones
// (gg/je/im/fo/yt/sh/tk/pn). The operator's core markets are pinned to
// the top; the rest is A→Z. Labels carry the code so typing either the
// name or the code finds the country.

export type CountryOption = { code: string; label: string };

const PRIORITY: CountryOption[] = [
  { code: "kz", label: "Kazakhstan (kz)" },
  { code: "ru", label: "Russia (ru)" },
  { code: "ua", label: "Ukraine (ua)" },
  { code: "by", label: "Belarus (by)" },
  { code: "uz", label: "Uzbekistan (uz)" },
];

const REST: CountryOption[] = [
  { code: "af", label: "Afghanistan (af)" },
  { code: "al", label: "Albania (al)" },
  { code: "dz", label: "Algeria (dz)" },
  { code: "as", label: "American Samoa (as)" },
  { code: "ad", label: "Andorra (ad)" },
  { code: "ao", label: "Angola (ao)" },
  { code: "ai", label: "Anguilla (ai)" },
  { code: "ag", label: "Antigua and Barbuda (ag)" },
  { code: "ar", label: "Argentina (ar)" },
  { code: "am", label: "Armenia (am)" },
  { code: "aw", label: "Aruba (aw)" },
  { code: "au", label: "Australia (au)" },
  { code: "at", label: "Austria (at)" },
  { code: "az", label: "Azerbaijan (az)" },
  { code: "bs", label: "Bahamas (bs)" },
  { code: "bh", label: "Bahrain (bh)" },
  { code: "bd", label: "Bangladesh (bd)" },
  { code: "bb", label: "Barbados (bb)" },
  { code: "be", label: "Belgium (be)" },
  { code: "bz", label: "Belize (bz)" },
  { code: "bj", label: "Benin (bj)" },
  { code: "bt", label: "Bhutan (bt)" },
  { code: "bo", label: "Bolivia (bo)" },
  { code: "ba", label: "Bosnia and Herzegovina (ba)" },
  { code: "bw", label: "Botswana (bw)" },
  { code: "br", label: "Brazil (br)" },
  { code: "vg", label: "British Virgin Islands (vg)" },
  { code: "bn", label: "Brunei (bn)" },
  { code: "bg", label: "Bulgaria (bg)" },
  { code: "bf", label: "Burkina Faso (bf)" },
  { code: "bi", label: "Burundi (bi)" },
  { code: "kh", label: "Cambodia (kh)" },
  { code: "cm", label: "Cameroon (cm)" },
  { code: "ca", label: "Canada (ca)" },
  { code: "cv", label: "Cape Verde (cv)" },
  { code: "ky", label: "Cayman Islands (ky)" },
  { code: "cf", label: "Central African Republic (cf)" },
  { code: "td", label: "Chad (td)" },
  { code: "cl", label: "Chile (cl)" },
  { code: "cn", label: "China (cn)" },
  { code: "co", label: "Colombia (co)" },
  { code: "cg", label: "Congo - Brazzaville (cg)" },
  { code: "cd", label: "Congo - Kinshasa (cd)" },
  { code: "ck", label: "Cook Islands (ck)" },
  { code: "cr", label: "Costa Rica (cr)" },
  { code: "ci", label: "Côte d'Ivoire (ci)" },
  { code: "hr", label: "Croatia (hr)" },
  { code: "cu", label: "Cuba (cu)" },
  { code: "cy", label: "Cyprus (cy)" },
  { code: "cz", label: "Czechia (cz)" },
  { code: "dk", label: "Denmark (dk)" },
  { code: "dj", label: "Djibouti (dj)" },
  { code: "dm", label: "Dominica (dm)" },
  { code: "do", label: "Dominican Republic (do)" },
  { code: "ec", label: "Ecuador (ec)" },
  { code: "eg", label: "Egypt (eg)" },
  { code: "sv", label: "El Salvador (sv)" },
  { code: "gq", label: "Equatorial Guinea (gq)" },
  { code: "ee", label: "Estonia (ee)" },
  { code: "et", label: "Ethiopia (et)" },
  { code: "fo", label: "Faroe Islands (fo)" },
  { code: "fj", label: "Fiji (fj)" },
  { code: "fi", label: "Finland (fi)" },
  { code: "fr", label: "France (fr)" },
  { code: "gf", label: "French Guiana (gf)" },
  { code: "pf", label: "French Polynesia (pf)" },
  { code: "ga", label: "Gabon (ga)" },
  { code: "gm", label: "Gambia (gm)" },
  { code: "ge", label: "Georgia (ge)" },
  { code: "de", label: "Germany (de)" },
  { code: "gh", label: "Ghana (gh)" },
  { code: "gi", label: "Gibraltar (gi)" },
  { code: "gr", label: "Greece (gr)" },
  { code: "gl", label: "Greenland (gl)" },
  { code: "gd", label: "Grenada (gd)" },
  { code: "gp", label: "Guadeloupe (gp)" },
  { code: "gu", label: "Guam (gu)" },
  { code: "gt", label: "Guatemala (gt)" },
  { code: "gg", label: "Guernsey (gg)" },
  { code: "gn", label: "Guinea (gn)" },
  { code: "gy", label: "Guyana (gy)" },
  { code: "ht", label: "Haiti (ht)" },
  { code: "hn", label: "Honduras (hn)" },
  { code: "hk", label: "Hong Kong (hk)" },
  { code: "hu", label: "Hungary (hu)" },
  { code: "is", label: "Iceland (is)" },
  { code: "in", label: "India (in)" },
  { code: "id", label: "Indonesia (id)" },
  { code: "iq", label: "Iraq (iq)" },
  { code: "ie", label: "Ireland (ie)" },
  { code: "im", label: "Isle of Man (im)" },
  { code: "il", label: "Israel (il)" },
  { code: "it", label: "Italy (it)" },
  { code: "jm", label: "Jamaica (jm)" },
  { code: "jp", label: "Japan (jp)" },
  { code: "je", label: "Jersey (je)" },
  { code: "jo", label: "Jordan (jo)" },
  { code: "ke", label: "Kenya (ke)" },
  { code: "ki", label: "Kiribati (ki)" },
  { code: "kw", label: "Kuwait (kw)" },
  { code: "kg", label: "Kyrgyzstan (kg)" },
  { code: "la", label: "Laos (la)" },
  { code: "lv", label: "Latvia (lv)" },
  { code: "lb", label: "Lebanon (lb)" },
  { code: "ls", label: "Lesotho (ls)" },
  { code: "ly", label: "Libya (ly)" },
  { code: "li", label: "Liechtenstein (li)" },
  { code: "lt", label: "Lithuania (lt)" },
  { code: "lu", label: "Luxembourg (lu)" },
  { code: "mg", label: "Madagascar (mg)" },
  { code: "mw", label: "Malawi (mw)" },
  { code: "my", label: "Malaysia (my)" },
  { code: "mv", label: "Maldives (mv)" },
  { code: "ml", label: "Mali (ml)" },
  { code: "mt", label: "Malta (mt)" },
  { code: "mq", label: "Martinique (mq)" },
  { code: "mr", label: "Mauritania (mr)" },
  { code: "mu", label: "Mauritius (mu)" },
  { code: "yt", label: "Mayotte (yt)" },
  { code: "mx", label: "Mexico (mx)" },
  { code: "fm", label: "Micronesia (fm)" },
  { code: "md", label: "Moldova (md)" },
  { code: "mc", label: "Monaco (mc)" },
  { code: "mn", label: "Mongolia (mn)" },
  { code: "me", label: "Montenegro (me)" },
  { code: "ms", label: "Montserrat (ms)" },
  { code: "ma", label: "Morocco (ma)" },
  { code: "mz", label: "Mozambique (mz)" },
  { code: "mm", label: "Myanmar (mm)" },
  { code: "na", label: "Namibia (na)" },
  { code: "nr", label: "Nauru (nr)" },
  { code: "np", label: "Nepal (np)" },
  { code: "nl", label: "Netherlands (nl)" },
  { code: "nc", label: "New Caledonia (nc)" },
  { code: "nz", label: "New Zealand (nz)" },
  { code: "ni", label: "Nicaragua (ni)" },
  { code: "ne", label: "Niger (ne)" },
  { code: "ng", label: "Nigeria (ng)" },
  { code: "nu", label: "Niue (nu)" },
  { code: "mk", label: "North Macedonia (mk)" },
  { code: "no", label: "Norway (no)" },
  { code: "om", label: "Oman (om)" },
  { code: "pk", label: "Pakistan (pk)" },
  { code: "ps", label: "Palestine (ps)" },
  { code: "pa", label: "Panama (pa)" },
  { code: "pg", label: "Papua New Guinea (pg)" },
  { code: "py", label: "Paraguay (py)" },
  { code: "pe", label: "Peru (pe)" },
  { code: "ph", label: "Philippines (ph)" },
  { code: "pn", label: "Pitcairn Islands (pn)" },
  { code: "pl", label: "Poland (pl)" },
  { code: "pt", label: "Portugal (pt)" },
  { code: "pr", label: "Puerto Rico (pr)" },
  { code: "qa", label: "Qatar (qa)" },
  { code: "re", label: "Réunion (re)" },
  { code: "ro", label: "Romania (ro)" },
  { code: "rw", label: "Rwanda (rw)" },
  { code: "ws", label: "Samoa (ws)" },
  { code: "sm", label: "San Marino (sm)" },
  { code: "st", label: "São Tomé and Príncipe (st)" },
  { code: "sa", label: "Saudi Arabia (sa)" },
  { code: "sn", label: "Senegal (sn)" },
  { code: "rs", label: "Serbia (rs)" },
  { code: "sc", label: "Seychelles (sc)" },
  { code: "sl", label: "Sierra Leone (sl)" },
  { code: "sg", label: "Singapore (sg)" },
  { code: "sk", label: "Slovakia (sk)" },
  { code: "si", label: "Slovenia (si)" },
  { code: "sb", label: "Solomon Islands (sb)" },
  { code: "so", label: "Somalia (so)" },
  { code: "za", label: "South Africa (za)" },
  { code: "kr", label: "South Korea (kr)" },
  { code: "es", label: "Spain (es)" },
  { code: "lk", label: "Sri Lanka (lk)" },
  { code: "sh", label: "St. Helena (sh)" },
  { code: "kn", label: "St. Kitts and Nevis (kn)" },
  { code: "lc", label: "St. Lucia (lc)" },
  { code: "vc", label: "St. Vincent and the Grenadines (vc)" },
  { code: "sr", label: "Suriname (sr)" },
  { code: "se", label: "Sweden (se)" },
  { code: "ch", label: "Switzerland (ch)" },
  { code: "tw", label: "Taiwan (tw)" },
  { code: "tj", label: "Tajikistan (tj)" },
  { code: "tz", label: "Tanzania (tz)" },
  { code: "th", label: "Thailand (th)" },
  { code: "tl", label: "Timor-Leste (tl)" },
  { code: "tg", label: "Togo (tg)" },
  { code: "tk", label: "Tokelau (tk)" },
  { code: "to", label: "Tonga (to)" },
  { code: "tt", label: "Trinidad and Tobago (tt)" },
  { code: "tn", label: "Tunisia (tn)" },
  { code: "tr", label: "Turkey (tr)" },
  { code: "tm", label: "Turkmenistan (tm)" },
  { code: "ug", label: "Uganda (ug)" },
  { code: "ae", label: "United Arab Emirates (ae)" },
  { code: "gb", label: "United Kingdom (gb)" },
  { code: "us", label: "United States (us)" },
  { code: "uy", label: "Uruguay (uy)" },
  { code: "vi", label: "U.S. Virgin Islands (vi)" },
  { code: "vu", label: "Vanuatu (vu)" },
  { code: "ve", label: "Venezuela (ve)" },
  { code: "vn", label: "Vietnam (vn)" },
  { code: "ye", label: "Yemen (ye)" },
  { code: "zm", label: "Zambia (zm)" },
  { code: "zw", label: "Zimbabwe (zw)" },
];

export const COUNTRIES: CountryOption[] = [...PRIORITY, ...REST];
